# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('tarifa', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('proprietario', models.CharField(max_length=200)),
                ('fabricacao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia', models.IntegerField(default=0)),
                ('hora', models.IntegerField(default=0)),
                ('risco', models.FloatField(default=1)),
                ('vel', models.IntegerField(default=40)),
            ],
        ),
        migrations.AddField(
            model_name='ano',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Carro'),
        ),
    ]
