# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0003_auto_20161123_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carro', models.IntegerField(default=0)),
                ('pkt', models.IntegerField(default=0)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('vel', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='pkt',
            field=models.IntegerField(default=0),
        ),
    ]
