# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0004_auto_20161127_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.FloatField(default=0)),
                ('dia', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='lat',
            new_name='gps',
        ),
        migrations.RemoveField(
            model_name='mes',
            name='tarifa',
        ),
        migrations.RemoveField(
            model_name='msg',
            name='lon',
        ),
        migrations.AddField(
            model_name='dia',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.Mes'),
        ),
    ]
